In [82]:
%matplotlib notebook

In [83]:
#setup and dependences

import pandas as pd
import os
import numpy as np

In [84]:
#files to load
guns_data= ("guns_output.csv")

#readfile
guns_file= pd.read_csv(guns_data)

guns_file.head()

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals,year,mon_num
0,2019-01,Alabama,29977.0,266.0,6671.0,5507.0,343.0,260,0.0,14.0,...,0.0,13.0,16.0,0.0,0.0,0.0,0.0,44989,2019,1
1,2019-01,Alaska,249.0,10.0,1877.0,1685.0,290.0,139,0.0,1.0,...,0.0,11.0,10.0,2.0,0.0,0.0,0.0,4582,2019,1
2,2019-01,Arizona,6004.0,533.0,11710.0,6865.0,1255.0,675,0.0,12.0,...,0.0,23.0,13.0,0.0,0.0,0.0,0.0,29039,2019,1
3,2019-01,Arkansas,2917.0,921.0,5108.0,5175.0,401.0,335,78.0,13.0,...,0.0,8.0,9.0,3.0,0.0,1.0,0.0,17258,2019,1
4,2019-01,California,34585.0,0.0,35861.0,23195.0,4035.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98502,2019,1

In [87]:
#create new df w/ dropped columns
#gapminder_ocean.drop(['pop', 'gdpPercap', 'continent'], axis=1)
all_permits_df= guns_file.drop(['permit_recheck',"multiple", "admin", "prepawn_handgun", "prepawn_long_gun",  
                "rentals_handgun", "rentals_long_gun", "private_sale_handgun", "private_sale_long_gun", 
                "private_sale_other", "return_to_seller_handgun", "return_to_seller_long_gun", "return_to_seller_other",
                'prepawn_other', 'redemption_handgun', 'redemption_long_gun', 'redemption_other', 'returned_handgun',
                'returned_long_gun', 'returned_other' ], axis=1)

all_permits_df

,month,state,permit,handgun,long_gun,other,totals,year,mon_num
0,2019-01,Alabama,29977.0,6671.0,5507.0,343.0,44989,2019,1
1,2019-01,Alaska,249.0,1877.0,1685.0,290.0,4582,2019,1
2,2019-01,Arizona,6004.0,11710.0,6865.0,1255.0,29039,2019,1
3,2019-01,Arkansas,2917.0,5108.0,5175.0,401.0,17258,2019,1
4,2019-01,California,34585.0,35861.0,23195.0,4035.0,98502,2019,1
5,2019-01,Colorado,7292.0,16417.0,11575.0,1796.0,38491,2019,1
6,2019-01,Connecticut,7748.0,5368.0,1945.0,788.0,16324,2019,1
7,2019-01,Delaware,558.0,1684.0,1473.0,141.0,4119,2019,1
8,2019-01,District of Columbia,253.0,101.0,5.0,0.0,360,2019,1
9,2019-01,Florida,18964.0,47372.0,18749.0,3651.0,97486,2019,1
10,2019-01,Georgia,21575.0,11780.0,7535.0,670.0,44839,2019,1
11,2019-01,Guam,0.0,122.0,42.0,11.0,181,2019,1
12,2019-01,Hawaii,1064.0,0.0,0.0,0.0,1068,2019,1
13,2019-01,Idaho,5153.0,3522.0,3602.0,414.0,13634,2019,1
14,2019-01,Illinois,16976.0,21587.0,10082.0,0.0,331325,2019,1
15,2019-01,Indiana,107476.0,17265.0,10423.0,1738.0,160140,2019,1
16,2019-01,Iowa,6401.0,128.0,1887.0,68.0,16067,2019,1
17,2019-01,Kansas,1982.0,5269.0,4584.0,688.0,13767,2019,1
18,2019-01,Kentucky,290432.0,8170.0,6213.0,510.0,308573,2019,1
19,2019-01,Louisiana,2357.0,8961.0,7473.0,844.0,21945,2019,1
20,2019-01,Maine,862.0,2652.0,2333.0,407.0,6682,2019,1
21,2019-01,Mariana Islands,0.0,9.0,11.0,4.0,25,2019,1
22,2019-01,Maryland,2758.0,4254.0,4473.0,100.0,11976,2019,1
23,2019-01,Massachusetts,12279.0,4016.0,2644.0,574.0,19812,2019,1
24,2019-01,Michigan,19011.0,8674.0,6844.0,800.0,35884,2019,1
25,2019-01,Minnesota,11526.0,8031.0,7106.0,1078.0,53145,2019,1
26,2019-01,Mississippi,1777.0,6833.0,5707.0,371.0,17416,2019,1
27,2019-01,Missouri,2194.0,16244.0,12657.0,1805.0,36657,2019,1
28,2019-01,Montana,1206.0,2097.0,2753.0,278.0,7695,2019,1
29,2019-01,Nebraska,4449.0,125.0,1711.0,32.0,6635,2019,1
...,...,...,...,...,...,...,...,...,...
13335,1998-11,Minnesota,9.0,27.0,280.0,NaN,319,1998,11
13336,1998-11,Mississippi,0.0,286.0,491.0,NaN,784,1998,11
13337,1998-11,Missouri,0.0,116.0,458.0,NaN,578,1998,11
13338,1998-11,Montana,0.0,101.0,98.0,NaN,201,1998,11
13339,1998-11,Nebraska,88.0,1.0,96.0,NaN,186,1998,11
13340,1998-11,Nevada,0.0,75.0,76.0,NaN,159,1998,11
13341,1998-11,New Hampshire,0.0,8.0,46.0,NaN,55,1998,11
13342,1998-11,New Jersey,0.0,20.0,53.0,NaN,77,1998,11
13343,1998-11,New Mexico,0.0,86.0,121.0,NaN,211,1998,11
13344,1998-11,New York,0.0,40.0,279.0,NaN,319,1998,11
13345,1998-11,North Carolina,524.0,87.0,695.0,NaN,1310,1998,11
13346,1998-11,North Dakota,0.0,20.0,38.0,NaN,58,1998,11
13347,1998-11,Ohio,0.0,502.0,434.0,NaN,952,1998,11
13348,1998-11,Oklahoma,0.0,259.0,361.0,NaN,633,1998,11
13349,1998-11,Oregon,0.0,153.0,186.0,NaN,344,1998,11
13350,1998-11,Pennsylvania,0.0,5.0,8.0,NaN,17,1998,11
13351,1998-11,Puerto Rico,0.0,1.0,1.0,NaN,2,1998,11
13352,1998-11,Rhode Island,0.0,13.0,23.0,NaN,38,1998,11
13353,1998-11,South Carolina,0.0,0.0,6.0,NaN,6,1998,11
13354,1998-11,South Dakota,0.0,8.0,66.0,NaN,74,1998,11
13355,1998-11,Tennessee,0.0,19.0,85.0,NaN,107,1998,11
13356,1998-11,Texas,0.0,1384.0,1349.0,NaN,2794,1998,11
13357,1998-11,Utah,0.0,98.0,169.0,NaN,267,1998,11
13358,1998-11,Vermont,0.0,23.0,35.0,NaN,59,1998,11
13359,1998-11,Virgin Islands,0.0,0.0,0.0,NaN,0,1998,11
13360,1998-11,Virginia,0.0,14.0,2.0,NaN,24,1998,11
13361,1998-11,Washington,1.0,65.0,286.0,NaN,361,1998,11
13362,1998-11,West Virginia,3.0,149.0,251.0,NaN,408,1998,11
13363,1998-11,Wisconsin,0.0,25.0,214.0,NaN,241,1998,11
13364,1998-11,Wyoming,8.0,45.0,49.0,NaN,107,1998,11

In [93]:
#bin by year and asum permits for each year
permit_groups= all_permits_df.groupby("month")
permit_sums= permit_groups["permit", 'handgun', 'long_gun', 'other'].sum()
permit_sums

            permit   handgun  long_gun     other
month
1998-11     2073.0    6859.0   11909.0       0.0
1998-12    76096.0  213140.0  570882.0       0.0
1999-01    77072.0  184496.0  309915.0       0.0
1999-02    84759.0  232448.0  352411.0       0.0
1999-03   103185.0  241036.0  376775.0       0.0
1999-04    90873.0  207093.0  323222.0       0.0
1999-05    80492.0  192021.0  281434.0       0.0
1999-06    79996.0  183471.0  286331.0       0.0
1999-07    70806.0  186675.0  303711.0       0.0
1999-08    82428.0  189920.0  402909.0       0.0
1999-09    85273.0  185025.0  508439.0       0.0
1999-10    92050.0  214798.0  601482.0       0.0
1999-11    92502.0  213347.0  664016.0       0.0
1999-12    98264.0  306408.0  806806.0       0.0
2000-01   100162.0  185677.0  322777.0       0.0
2000-02    99914.0  214980.0  357950.0       0.0
2000-03   116872.0  219150.0  368699.0       0.0
2000-04   102060.0  180538.0  307934.0       0.0
2000-05    99202.0  161115.0  249427.0       0.0
2000-06   101311.0  163593.0  259291.0       0.0
2000-07    94508.0  154169.0  270179.0       0.0
2000-08   109975.0  166799.0  381778.0       0.0
2000-09   101460.0  164780.0  488916.0       0.0
2000-10   110765.0  168669.0  536428.0       0.0
2000-11   100761.0  181410.0  587781.0       0.0
2000-12    90824.0  230999.0  648818.0       0.0
2001-01   114906.0  179114.0  323133.0       0.0
2001-02   111219.0  192931.0  344365.0       0.0
2001-03   129897.0  199519.0  373490.0       0.0
2001-04   106439.0  162839.0  300907.0       0.0
...            ...       ...       ...       ...
2016-08   542822.0  611575.0  471095.0   41026.0
2016-09   744512.0  533709.0  486524.0   40501.0
2016-10   858875.0  634504.0  576371.0   56125.0
2016-11   803158.0  748430.0  745659.0   65418.0
2016-12   842154.0  844966.0  795473.0  111710.0
2017-01   912220.0  562597.0  366099.0   31788.0
2017-02   836331.0  717930.0  421678.0   33386.0
2017-03   945715.0  751866.0  461273.0   38684.0
2017-04   837426.0  623448.0  376484.0   32577.0
2017-05   830963.0  552018.0  328157.0   29372.0
2017-06   800655.0  569149.0  331152.0   29730.0
2017-07   754920.0  480124.0  322264.0   26898.0
2017-08   789993.0  507489.0  396950.0   27631.0
2017-09   761622.0  478082.0  417305.0   26924.0
2017-10   805954.0  519980.0  480203.0   37445.0
2017-11   820971.0  680029.0  635407.0   39297.0
2017-12   844914.0  784267.0  697785.0   46261.0
2018-01   914077.0  501638.0  337597.0   35971.0
2018-02   890756.0  661699.0  434373.0   46931.0
2018-03  1047107.0  781452.0  540979.0   68192.0
2018-04   926998.0  563601.0  375946.0   45929.0
2018-05   876501.0  488120.0  300466.0   36560.0
2018-06   826105.0  474159.0  291522.0   35114.0
2018-07   816098.0  436969.0  276793.0   31233.0
2018-08   849294.0  478723.0  361705.0   31818.0
2018-09   773679.0  434660.0  370532.0   31624.0
2018-10   799959.0  460017.0  417788.0   32649.0
2018-11   770662.0  582708.0  568336.0   45593.0
2018-12   737926.0  712365.0  640496.0   52685.0
2019-01   820224.0  514319.0  345768.0   46084.0

[243 rows x 4 columns]